name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and test (dev)
        run: |
          docker build -t tzetzo/docker-react-test -f Dockerfile.dev .
          docker run -e CI=true tzetzo/docker-react-test npm test -- --watchAll=false

      - name: Build production image
        run: docker build -t tzetzo/docker-react-prod -f Dockerfile .